'\" t
.\"     Title: repo-link-duplicates
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2014
.\"    Manual: Globus Toolkit Manual
.\"    Source: globus-release-tools
.\"  Language: English
.\"
.TH "REPO\-LINK\-DUPLICAT" "1" "09/08/2014" "globus\-release\-tools" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
repo-link-duplicates \- Hardlink identical binary packages
.SH "SYNOPSIS"
.sp
\fBrepo\-link\-duplicates\fR [\-h | \-\-help]
.sp
\fBrepo\-link\-duplicates\fR [OPTIONS]
.SH "DESCRIPTION"
.sp
The \fBrepo\-link\-duplicates\fR replaces identical binary package identical files in a directory tree with hard links\&. It only considers duplicates of *\&.tar\&.gz, *\&.deb, and *\&.rpm files\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Show a help message and exit
.RE
.PP
\fB\-r ROOT, \-\-root ROOT\fR
.RS 4
Link duplicates based in the ROOT directory
.RE
.SH "SEE ALSO"
.sp
repo\-sync\-unstable(1)
.SH "AUTHOR"
.sp
Copyright \(co 2014 University of Chicago
