'\" t
.\"     Title: repo-promote-package
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 09/10/2014
.\"    Manual: Globus Toolkit Manual
.\"    Source: globus-release-tools
.\"  Language: English
.\"
.TH "REPO\-PROMOTE\-PACKA" "1" "09/10/2014" "globus\-release\-tools" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
repo-promote-package \- Promote a package to a more stable release point
.SH "SYNOPSIS"
.sp
\fBrepo\-promote\-package\fR [\-h | \-\-help]
.sp
\fBrepo\-promote\-package\fR [OPTIONS]
.SH "DESCRIPTION"
.sp
The \fBrepo\-promote\-package\fR program copies binary and source packages within \fBROOT\fR, from one release (unstable, testing, stable) to another\&. If a \fBPACKAGE\fR is specified in the command\-line options, then only that package name is processed (including sub\-packages such as \fI\-doc\fR and \fI\-dev\fR packages\&. Otherwise, all newer (by version number) packages are copied\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Show a help message and exit
.RE
.PP
\fB\-r ROOT, \-\-root ROOT\fR
.RS 4
Synchronize packages to the ROOT directory
.RE
.PP
\fB\-c CACHE, \-\-cache CACHE\fR
.RS 4
Cache files in CACHE directory
.RE
.PP
\fB\-p PACKAGE, \-\-package PACKAGE\fR
.RS 4
Only promote the latest version of PACKAGE
.RE
.PP
\fB\-f RELEASE, \-\-from RELEASE\fR
.RS 4
Copy packages from RELEASE (unstable or testing)
.RE
.PP
\fB\-to RELEASE, \-\-to RELEASE\fR
.RS 4
Copy packages to the RELEASE (testing or stable)
.RE
.PP
\fB\-d, \-\-dryrun\fR
.RS 4
Display packages that would be copied, but don\(cqt actually execute the copy
.RE
.PP
\fB\-a ADVISORY, \-\-advisory ADVISORY\fR
.RS 4
Add new package changelogs to the ADVISORY file\&. This is ignored if the "to" RELEASE is not
\fIstable\fR\&.
.RE
.SH "SEE ALSO"
.sp
repo\-sync\-unstable(1)
.SH "AUTHOR"
.sp
Copyright \(co 2014 University of Chicago
